### ISSUE TITLE
Artefacts in true colour

### ISSUE THREAD

**Issue by howff** [ssec/polar2grid#143]
See the scattering of cyan (and other colour) pixels in the northern areas of example from MODIS Terra
(seem to be only in the sea as far as I can tell. Sadly IPOPP gives similar artefacts but in cloud areas!)

https://wetransfer.com/downloads/740141799d087524c0cb1ff23f6cbdd120180125124103/95f80442dd1b968b5a6ef49399de5ab920180125124103/0b1fcb

**Comment by davidh-ssec** [comment]
Very interesting. Just for historical purposes I'm pasting a screenshot of the bad parts of the image. I had thought we fixed all issues related to this. There is always a chance it is in the data.

1. What command are you using to generate this image?
2. Have you seen it in more than one case?
3. What about different times of the year?
4. Have you ever seen it in lower latitudes?
5. Is this direct broadcast data?

![image](https://user-images.githubusercontent.com/1828519/35394124-7ac97aae-01ac-11e8-8307-e36ee9190d9b.png)

**Comment by howff** [comment]
Yes it's DB data but I'm not convinced that it's in the data for two reasons: it occurs in various parts of the image, and it only seems to occur in dark areas but if it was caused by noise it would occur in clouds too. However it doesn't occur everywhere which is odd. I've just tried polar2grid v2.2 (released today) and it still occurs but different places from the old version which also suggests it's not the data itself.
Comparison image: new p2g is on the left. This region is a lower latitude about 56 degrees.
![screenshot from 2018-01-26 12 28 35](https://user-images.githubusercontent.com/3064316/35441724-84952772-029c-11e8-9f25-710d2c253452.png)

The artefacts seem to be surrounding dark area, the edges of them.

Raw data:
geo, 250m, 500m
https://wetransfer.com/downloads/cf598e3970fb2de5c4b0c594ac1ddcbe20180126133149/105a689558dfe88c8b01cb1355719ff320180126133149/bdf8f7

1000m
https://wetransfer.com/downloads/ed2a3144a3a54ca4c395d4e58357fb3620180126133524/46fd1d42fc130093fe9c02d7a10645e520180126133524/c74281

crefl
https://wetransfer.com/downloads/9329bb8584f40e02e96979a597c887a320180126133704/7ba249df99fb32d59110fd870b4930ad20180126133704/a98763

**Comment by davidh-ssec** [comment]
Their will be small differences between v2.1 and v2.2 for MODIS. The fix for the prime meridian shifted/smashed pixels was fixed by using 64-bit floats to interpolate the high resolution MODIS geolocation. I'm 99% sure this is why the blue artifact is slightly different in the new version of P2G.

**Comment by davidh-ssec** [comment]
Good news (?), I was able to reproduce these bright pixels locally. When I get time I'll look in to the individual bands and see if I can determine if the bands are the cause. My current guess is that one of the low resolution bands has bright pixels that, when resampled to the same resolution, are being shown along with dark high resolution pixels.

**Comment by davidh-ssec** [comment]
@howff Could you try specifying `--maximum-weight-mode` with your P2G call that makes these true colors? In my simple test this gets rid of the cyan pixels. This makes the EWA resampling very similar to a nearest neighbor algorithm. This doesn't necessarily mean that there is an error with EWA resampling, but it does mean I have more to look at.

**Comment by howff** [comment]
I have made several tests:
- with and without --maximum-weight-mode
- with bilinear and ewa resampling
- with fornav-D=10 and =40

Observations:
- Difference images show that D=10 and D=40 produce different results but I can't see the difference side-by-side.
- maximum-weight-mode does remove the artefacts.
- bilinear also removes the artefacts (at least in the areas where I looked)
- I can see a difference between bilinear and maximum-weight-mode fairly clearly but I cannot tell which one is more 'correct'.
- All options except the default (which is 'ewa' and without m-w-m) look worse to me, so I've attached an image showing what I mean. The default is softer, smoother, more visually appealing, and all other combination of options is harsh, ragged.

![polar2grid_2018-02-06_11-36-22](https://user-images.githubusercontent.com/3064316/35861391-6f8d9444-0b3f-11e8-8a66-05723904e2d8.png)

**Comment by davidh-ssec** [comment]
We have been discussing this on the satpy slack channel (in addition to issues with pyspectral's own issues with rayleigh correction). The issue seems to be related to two things from what I've found:

1. I assumed the crefl output was valid from 0 to 32765 in the HDF4 files that the C software produces. This means that the minimum reflectance is 0 when scaled back to reflectance values. However, crefl actually produces data as low as -100 so -0.01.
2. The ratio used in the ratio sharpening does not handle negative reflectances in any special way. In your case there are regions where the reflectances are so low that the I01 band may be negative while the M05 band is positive. This resulted in a negative ratio which was used on the M04 and M03 bands resulting in negative (possibly large) reflectances in those areas.

After fixing these two issues the images look as expected. We are still trying to decide what the best fix is for number 2. To do the absolute value of the ratio seems wrong. I've been leaning towards making the ratio 1 anywhere the ratio is negative or some similar solution.

**Comment by davidh-ssec** [comment]
@howff I think I've fixed this in P2G and we will probably release a new bugfix version 2.2.1. I don't have any idea when that would come out since we're still waiting for feedback from some heavy users. If you would like I can get you an early tarball for you to test the fix with. Let me know if you're interested in a prerelease tarball.

**Comment by howff** [comment]
Thanks for your help! I picked the two relevant commits (rgb.py and crefl2swath.py) and made the changes directly in my copy so you don't need to prepare a tarball. A quick test and the artefacts are gone, thank you.
